### ISSUE TITLE
How to keep sync between OO relations and FK

### ISSUE THREAD

**Issue by fmcarvalho** [tdx96/Rapper#16]
Every FK can be implemented in OO in two possible ways. If `Job` has FK to `Account` then: 

* `Account` may have **multiples** `Job` objects
* `Job` may have one single `Account`

We may have both or just one of the relations. Or, at least, I would say that we should always have the single relation for update purposes on DB (insert, delete and update) and for facility we may also have the multiple relation, but read-only in this case. 

Whenever a `Job` is updated the corresponding SQL command takes the `accountId` and if that `Account` also has that `Job` in its list then it should be invalidated in the identity map.

**Comment by Joao360** [comment]
When we are creating/updating a `Job` instead of invalidating the IdentityMap, we will go to the `Account`, and then we call `thenApply` on the `CompletableFuture<List<Job>>` to add that job to the `List<Job>`  of the `Account`.

On the other hand, when we a `Job` is deleted we have to make the same update but to remove an entry of the `List<Job>`  of the `Account`.

!!! **The single relation is mandatory to reflect DB updates**. The multiple relation is optional and is according the above description!!!
